### ISSUE TITLE
Follow "Use Schnorr signatures" in preferences

### ISSUE THREAD

**Issue by imaginaryusername** [cculianu/electron_cash_scheduled_payments_plugin#5]
I got a scheduled payment out almost immediately after the upgrade, with preferences checked to Use Schorr Signature on 4.0.3 preview, but it seems like Scheduled Payment isn't following that. 

Minor nit, but will be nice if fixed, perferably while maintaining compatibility with < 4.0.2.

**Comment by cculianu** [comment]
Ok. I'll do this at some point soon.  Good point.  It's definitely possible and not hard to make it "version aware" and respond appropriately... and also respect the schnorr sig thing.

**Comment by cculianu** [comment]
This has now been implemented in v1.5 which has just been released.

Note v1.5 is required if you are using the latest EC git head or after we release 4.0.6 soon (due to the icon file change).
